"use client";

import type { Metadata } from "next";
import type { ReactNode } from "react";
import { QueryClient, QueryClientProvider } from "@tanstack/react-query";
import { UserProvider } from "@/context/user-context";
import { Layout } from "@/components/layout";
import "./globals.css";

const queryClient = new QueryClient();

const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: ReactNode;
}>) {
  return (
    <html lang="en">
      <head />
      <body className="antialiased">
        <QueryClientProvider client={queryClient}>
          <UserProvider>
            <Layout>{children}</Layout>
          </UserProvider>
        </QueryClientProvider>
      </body>
    </html>
  );
}
